### ISSUE TITLE
Android > Settings Screen > Logout > "Are You Sure" alert 

### ISSUE THREAD

**Issue by corblng** [LibertyDSNP/dsnp-wallet-kotlin#109]
**Narrative:** 
As a user, when I tap the Log Out button, I would like to see a popup that confirms my choice and reminds me about the importance of backing up my recovery phrase, so that I am aware of the risk and have a chance to double check that I backed up my recovery phrase. 

**Overview:** 
When a user taps on Log Out button (located in the Settings screen), we want to show an "Are You Sure" alert that reminds the user about the importance of backing up their recovery phrase. 

**Figma Link**
https://www.figma.com/file/PDzDCWcPnZ8EFmwf5FkkBn/Amplica-Pro---MVP?type=design&node-id=515%3A12579&mode=design&t=74A6IsHCFuCrRS6f-1

**Requirements**
* When user taps the "Log Out" button located in the Settings screen, show an alert as it appears in figma. 
* Tapping "View Recovery Phrase" should direct the user to the Backup Phrase screen. 
* Tapping Log Out should delete the users wallet account and associated keys.

**Comment by VitaliKrasnik** [comment]
A few UI fixes are needed. 

1. Use center aligning for the text 
2. Add a bit more 'breathing room' at the bottom (padding needs to be increased)

App Center build: 77

![image.png](https://images.zenhubusercontent.com/63d2ba5f1ae88085c27b0f0f/2c48f798-2adc-45e4-84eb-daee0719567c)

**Comment by VitaliKrasnik** [comment]
For the alert's message please use the center alignment as shown in the design doc, now it uses left  alignment.
Actual result
[image.png](https://images.zenhubusercontent.com/63d2ba5f1ae88085c27b0f0f/d4dafec8-d591-4e5c-b548-6f65d7e02133)
Design 
![image.png](https://images.zenhubusercontent.com/63d2ba5f1ae88085c27b0f0f/28015309-f27c-467c-975c-3f37590c1e56)

**Comment by VitaliKrasnik** [comment]
Test Build : 87
