### ISSUE TITLE
Android > App crashes when tapping on Backup Seed Phrase

### ISSUE THREAD

**Issue by corblng** [LibertyDSNP/dsnp-wallet-kotlin#122]
**Issue**: 
Wallet app crashes when tapping on "Backup Seed Phrase" button 

**Overview**:
After creating a user handle and tapping entering the Social Identity Progress screen through "Congrats" modal, the app will crash when the "Backup Seed Phrase" button is pressed.  Seems to only crash when going through the "Congratulations" modal. Entering recovery phrase backup flow directly from settings does not crash the app. 

**Device Info:** 
Device Samsung Galaxy Fold 4. Android 13

**Build Info:** 
Dev build - July 12, 2023

**Steps:**
1. Launch app and create a handle. 
2. Tap on "Get Started" from congrats modal. 
3. Tap on Backup Recovery Phrase.  

**Expected result:** 
User should be directed to the Backup Recovery Phrase flow. 

**Actual Result:** 
Application crashes.

**Comment by VitaliKrasnik** [comment]
@corblng  could you please test this bug again using your device? 
Please use build 78 and later in the [app center](https://appcenter.ms/orgs/Unfinished/apps/standalone-wallet-dev/distribute/releases?top=false)

**Comment by corblng** [comment]
Confirming that the app no longer crashes.
