### ISSUE TITLE
Android > getMsaId

### ISSUE THREAD

**Issue by DannyAhmedApex** [LibertyDSNP/dsnp-wallet-kotlin#16]

**Comment by VitaliKrasnik** [comment]
![image.png](https://images.zenhubusercontent.com/63d2ba5f1ae88085c27b0f0f/f935d5af-3dfe-4d36-9078-09bead56bd82)

![image.png](https://images.zenhubusercontent.com/63d2ba5f1ae88085c27b0f0f/0268c425-0e42-4898-acce-e0a833c60457)

![image.png](https://images.zenhubusercontent.com/63d2ba5f1ae88085c27b0f0f/bc575364-ce60-4626-af91-80c0aa87e6e2)
