### ISSUE TITLE
Android  > UI defects that were found on Samsung device

### ISSUE THREAD

**Issue by VitaliKrasnik** [LibertyDSNP/dsnp-wallet-kotlin#36]
Environment: 
Samsung galaxy S20
Android 12

1. The font is white on Samsung s22
2. Edges of the screen are not visible (Not responsive)
3. Cells of the Seed phrase are not responsive. 
4. Create new ID button Doesn't work 

![image.png](https://images.zenhubusercontent.com/63d2ba5f1ae88085c27b0f0f/2542a8cf-27d0-4085-b9d4-62e1e7c7275a)

![image.png](https://images.zenhubusercontent.com/63d2ba5f1ae88085c27b0f0f/19577ca1-ecaa-486d-99b1-6b7ffa541277)

![image.png](https://images.zenhubusercontent.com/63d2ba5f1ae88085c27b0f0f/e2471e1f-7763-4290-8019-c95963e16b56)

![image.png](https://images.zenhubusercontent.com/63d2ba5f1ae88085c27b0f0f/fc383a2b-c017-423a-98f6-37cf7eb84641)

**Comment by DannyAhmedApex** [comment]
@VitaliKrasnik can we close this issue as It's not valid anymore because we are now using new UI framework compose.
