### ISSUE TITLE
Android > Extrinsic Error Handling

### ISSUE THREAD

**Issue by DannyAhmedApex** [LibertyDSNP/dsnp-wallet-kotlin#44]
The code we're relying on from Nova returns the result of if the extrinsic was executed, but not any errors within the extrinsic.

E.g. CreateMSA twice for the same user, and we won't experience any issues.

The same goes for transferring tokens to a bad account.

We'll need to figure out how to dive deeper into the extrinsic, despite only having the transactionHash.

**Comment by DannyAhmedApex** [comment]
@VitaliKrasnik It's for error suppose if msa id is already created then shows error to user that msa id exists

**Comment by VitaliKrasnik** [comment]
0. The get Event Info button crashes the app on any device or emulator.  

1. When I click to create an MSA ID, I see only the block hash value.  But not the ID 
2. MSA ID submit and WATCH? does show any message and it's not clear what it does
3. Getting a public key to MSA is not clear what it does. 

![image.png](https://images.zenhubusercontent.com/63d2ba5f1ae88085c27b0f0f/936fe9bc-3511-4bb2-8984-dfecfd44642f)

**Comment by DannyAhmedApex** [comment]
I am checking these points will update you soon
