### ISSUE TITLE
Android > Welcome Screen

### ISSUE THREAD

**Issue by crbnlng** [LibertyDSNP/dsnp-wallet-kotlin#5]
**Narrative** 
As a user, I would like to see a welcome screen when I open the standalone wallet app, so that I can begin setting up my DSNP ID. 

**Overview** 
This story is to create a welcome screen so that users can decide if they want to. 
1. Lookup an Existing DSNP ID 
2. Create a New DSNP ID
3. Restore DSNP wallet

Figma Link: 
https://www.figma.com/file/JacuBzETlFr0VNjBQKKRgi/Wallet-Concepts?node-id=1276%3A5074&t=GxoyoBgW8ek8Y4Rw-1

**Requirements**

- Create Landing screen as specified in Figma. 
- Screen should contain 3 button options: 
- 1. I have a DSNP ID
- 2. Create DSNP ID 
- 3. Restore DSNP Wallet  
- Screen should contain "Terms" link and "Privacy Policy" link. Tapping on link should open webview. 
- Placeholder Privacy Link: https://www.dsnp.org/privacy.html
- Placeholder Terms Link: https://www.dsnp.org/privacy.html

**Comment by VitaliKrasnik** [comment]
Bug 1 (UI) 
The Privacy and Terms Links are not visible on the Welcome screen. User have to scroll the page to view them 
Device: Pixel 6

Low severity
Low priority

**Comment by VitaliKrasnik** [comment]
Bug 2 
I have a DSNP ID - button doesn't open the Look Up the account screen. The Create DSNP ID does it instead.

**Comment by DannyAhmedApex** [comment]
I have a DSNP ID: It's a different flow currently It's not developed yet so I just shows a toast message that it's in progress @VitaliKrasnik

**Comment by DannyAhmedApex** [comment]
Bug 1: Checking..

**Comment by DannyAhmedApex** [comment]
Bug 1: I checked It's fine as some screen size is small so the scrollview enabled to interact with other elements as It can't be adjusted on available screen size

Can you add any screenshot regarding that screen to see more the bug @VitaliKrasnik
