### ISSUE TITLE
Android > Onboarding > Landing Screen

### ISSUE THREAD

**Issue by crbnlng** [LibertyDSNP/dsnp-wallet-kotlin#50]
**Narrative**:
As a user, when I launch Amplica Connect, I would like to see a landing page, so that I can see and overview of what Amplica Connect is and how to get started.

**Overview:**
This story is to build out the landing page screen.

**Figma Link:**
https://www.figma.com/file/PDzDCWcPnZ8EFmwf5FkkBn/Amplica-Pro---MVP?type=design&node-id=1%3A1952&t=cMVKrSCRSubauYDz-1

**Requirements:**
* Screen design and styling should match Figma spec.
* User should see 3 buttons: Create Identity, I have an ID, Restore Account
* User should see a footer with text link buttons for Terms and Privacy Policy. *Link destinations TBD. For now, when tapped please show "Coming Soon" alert.

**Comment by DannyAhmedApex** [comment]
This ticket has been covered in XML UI. Now @jmiecz is refactoring into Jetpack Compose.

**Comment by VitaliKrasnik** [comment]
Please fix the following issues:
1. optimize the buttons’ touch area it is too small

**Comment by jmiecz** [comment]
@corblng The screenshot @VitaliKrasnik shared, is that the outdated one? I've syncd with Heather and was told what we have on the right golden. 

@VitaliKrasnik `optimize the buttons’ touch area it is too small` not sure what this means

**Comment by VitaliKrasnik** [comment]
Removed issues, please just increase the touch area of the buttons. @jmiecz

**Comment by VitaliKrasnik** [comment]
All issues are fixed.
