### ISSUE TITLE
Android > Onboarding Screens > Custodial User Migration

### ISSUE THREAD

**Issue by crbnlng** [LibertyDSNP/dsnp-wallet-kotlin#51]
**Narrative**:
As a Amplica Access custodial wallet user, I would like to be able to migrate to the stand alone wallet, so that I can have full control over my social identity, keys and social graph. 

**Overview**: 
This story is to build out support for migrating a user from the custodial wallet to the stand alone wallet. 

**Figma Link:** 
https://www.figma.com/file/PDzDCWcPnZ8EFmwf5FkkBn/Amplica-Pro---MVP?type=design&node-id=1%3A1952&t=cMVKrSCRSubauYDz-1

**Requirements**: 
* Create screens as shown in Figma link. 
* When the user taps on the "I have an ID" button located on the app "Landing Screen", then direct user to "https://www.amplicaaccess.com" in a Chrome custom tab.  *Note* Website functionality does not currently exist so we won't be able to migrate users at this time.

**Comment by VitaliKrasnik** [comment]
Tested and closed
