### ISSUE TITLE
Android > Onboarding Screens > Create Identity - Claim Handle Screen 

### ISSUE THREAD

**Issue by crbnlng** [LibertyDSNP/dsnp-wallet-kotlin#52]
**Narrative**:
As a user, I can create a user handle for my social identity, so that I can be discoverable on the social web

**Overview**:
This story is to build the "Claim Handle" screen. When a user chooses to create an identity in the Amplica Connect app, we want to provide them the option to create a user handle.

**Figma Link:**
https://www.figma.com/file/PDzDCWcPnZ8EFmwf5FkkBn/Amplica-Pro---MVP?type=design&node-id=1%3A1549&t=MAs8VPiO4MGHe5Rd-1

**Requirements:**
* Tapping on "Create Social Identity" in the app "Landing screen" should direct user to the "Claim Handle" screen.
* Tapping / pressing "Back" button should return user to app "Landing Screen"
* Screen design and copy should match what is displayed in Figma
* Tapping on SKIP button should let user skip the handle creation and proceed to the "Create ID Success" screen.
* Auto select text field and show keyboard on entry to "Claim Handle" screen.
* Handle length should be 4-16 characters. 
* Once minimum character requirements are met, then "Next" button should become tappable.
* Tapping on the "Next" button should direct user to the Confirm handle screen. Handle suffix should be displayed.

**Comment by DannyAhmedApex** [comment]
This ticket has been covered in XML UI. Now @jmiecz is refactoring into Jetpack Compose.

**Comment by VitaliKrasnik** [comment]
1. The element should be a full-size page but it is shown as a card to the user, you can see it when hiding the keyboard  (Screenshot 1)
2. “skip for now” link is missing  (Screenshot 1)
3. Handle should contain 4-16 characters, but the app accepts less than 4 and more than 16 characters, please make the button disabled when a user enters less than 4 characters long input and restrict any input of more than 16 characters (screenshot 2 and 3 )
4. Please increase the “next” button tap area



![image.png](https://images.zenhubusercontent.com/63d2ba5f1ae88085c27b0f0f/49546428-b745-4163-8d09-c2bf2d411ca5)![image.png]

![image.png](https://images.zenhubusercontent.com/63d2ba5f1ae88085c27b0f0f/462dd8da-3627-4b87-8318-9cfd19211876)![image.png]

![image.png](https://images.zenhubusercontent.com/63d2ba5f1ae88085c27b0f0f/f6682e28-bca2-496e-b74f-a066df913a91)

**Comment by VitaliKrasnik** [comment]
5. Special characters shouldn't be removed except for an underscore.   
![image.png](https://images.zenhubusercontent.com/63d2ba5f1ae88085c27b0f0f/7410973e-6868-44c1-9743-dcb028cc255f)

**Comment by jmiecz** [comment]
@corblng I think @VitaliKrasnik has outdated screenshots? Sync with Heather and was told design was golden.

@corblng did we hear back on the handle? Right now, there is only a blank check for this field. Should we have local checks?

**Comment by VitaliKrasnik** [comment]
Updated the reports

**Comment by jmiecz** [comment]
@VitaliKrasnik 
1. The element should be a full-size page but it is shown as a card to the user, you can see it when hiding the keyboard  (Screenshot 1)
     This is not a fullscreen per Heather
2. “skip for now” link is missing  (Screenshot 1)
     Skip is being removed per @corblng 
3. Handle should contain 4-16 characters, but the app accepts less than 4 and more than 16 characters, please make the button disabled when a user enters less than 4 characters long input and restrict any input of more than 16 characters (screenshot 2 and 3 )
     This will be fixed once feature/52-bug-fixes merges in
4. Please increase the “next” button tap area
     The entire button is already the tap area, how much bigger does that need to get? Keep in mind that this button is the same button used throughout the entire app.

**Comment by hfinney** [comment]
@VitaliKrasnik - I know there was some discussion on #1 but I think we decided in planning last week to make it a bottom sheet. So I think it's good as is.

**Comment by VitaliKrasnik** [comment]
Got it, thank you for the clarification. All issues have been resolved. 
Except for the special characters. The handle must consist of letter numbers and underscores. But it still accepts special characters like !@#
@jmiecz  could you please fix it?
