### ISSUE TITLE
Android > Onboarding Screens > Create Identity - Agree to Terms Screen

### ISSUE THREAD

**Issue by crbnlng** [LibertyDSNP/dsnp-wallet-kotlin#53]
**Narrative:** 
As a user, I would like to see what permissions Amplica Connect is asking for, so that I'm aware of what info I'm agreeing to share. 

**Overview:** 
This story is to create the Agree to Terms screen. The goal of this screen is to show the user what permissions are being requested from the provider. Permissions can vary based on capabilities of the app.  

**Figma Link**
https://www.figma.com/file/PDzDCWcPnZ8EFmwf5FkkBn/Amplica-Pro---MVP?type=design&node-id=1%3A1889&t=u9nTGHvdFEscht39-1

**Requirements**
* Design and UI should match figma comp 

* Footer should be displayed with link buttons that go to: Terms, Privacy Policy and Learn More.  *Note* Link destinations are still TBD. 
Terms Link: https://www.amplicaaccess.com/access_web/terms.html
Privacy Link: https://www.amplicaaccess.com/access_web/privacy.html

**Comment by VitaliKrasnik** [comment]
@corblng  I don't see the Terms, and Privacy Policy link in the design document. Is it what needs to be added?

**Comment by VitaliKrasnik** [comment]
Learn more - link is missing on the UI 
![image.png](https://images.zenhubusercontent.com/63d2ba5f1ae88085c27b0f0f/6053418d-e8e4-45f1-821d-cafd8bf7dda0)

**Comment by corblng** [comment]
@VitaliKrasnik  We can use Terms Link: https://www.amplicaaccess.com/access_web/terms.html  and Privacy Policy: https://www.amplicaaccess.com/access_web/privacy.html  for now.

**Comment by VitaliKrasnik** [comment]
Tested Appcenter Build: 84
