### ISSUE TITLE
Android > Onboarding Screens > Create Identity - Congratulations Banner

### ISSUE THREAD

**Issue by crbnlng** [LibertyDSNP/dsnp-wallet-kotlin#54]
**Narrative:** 
As a user, once I create my social identity, I would like to see a banner that let's me know the process is complete and what I should do next. 

**Overview:** 
This story is to build a banner that let's the user know they have completed the initial social identity creation. The goal of the banner is to inform the user that their social identity was created and what they can do next. 

**Figma Link**
https://www.figma.com/file/PDzDCWcPnZ8EFmwf5FkkBn/Amplica-Pro---MVP?type=design&node-id=1%3A2961&t=u9nTGHvdFEscht39-1

**Requirements**
* Create banner UI and copy as defined in figma spec. 
* Banner should contain a close button. If tapped, the banner should be dismissed. 
* Display a button "Let's Go". Tapping the button should direct user to the Social Identity screen where the user can choose to complete filling out their profile. 
* Create a text button link for "Skip". Tapping this button should dismiss the banner.

**Comment by VitaliKrasnik** [comment]
Accepted but the social identity screen is not implemented yet
