### ISSUE TITLE
Android > Seed Phrase Flow Updates

### ISSUE THREAD

**Issue by crbnlng** [LibertyDSNP/dsnp-wallet-kotlin#57]
**Narrative:** 
As a user, I would like to see my seed phrase at my convenience, so that I can ensure I have it written down and backed up securely. 

**Overview:** 
This story is for creating and updating the seed phrase flow. 

**Figma Link**
Settings Screen: 
https://www.figma.com/file/PDzDCWcPnZ8EFmwf5FkkBn/Amplica-Pro---MVP?type=design&node-id=1%3A1804&t=cMVKrSCRSubauYDz-1

Seed Phrase Flow: 
https://www.figma.com/file/PDzDCWcPnZ8EFmwf5FkkBn/Amplica-Pro---MVP?type=design&node-id=1%3A1295&t=cMVKrSCRSubauYDz-1

**Requirements**
* Create bottom bar button labeled "Settings" 
* Tapping on Settings bottom bar button should display Settings screen with "Reveal Recovery Phrase" button. 
* Tapping on "Reveal Recovery Phrase" button should direct user to the "There will be a test" flow. 
* Display a "Back" button that allows the user to return to the Settings screen when. tapped. 
* Update the flow to match figma designs. 
* If user enters incorrect seed phrase, reset the puzzle and show message toast indicating there was an error "The recovery phrase you entered is incorrect. Please try again." 
* If user enters the correct seed phrase. Show message "Congratulations!" and direct user back to the Settings screen with "Complete" message.

**Comment by VitaliKrasnik** [comment]
Samsung S20 Wraps words that are too long.  (Please check the attached screenshot)
Suggestion maybe you could make the entire section bit wider, I think you have some space on the sides, but maybe Heather also has some recommendations for that. 

![image.png](https://images.zenhubusercontent.com/63d2ba5f1ae88085c27b0f0f/8e7e2b26-b248-41a6-af7d-dfdcd8a3c8f1)

**Comment by VitaliKrasnik** [comment]
Also @corblng  please ckeck the font we are using, some words look not ideally clear. It's a screenshot from a device so in reality it looks even smaller 

![image.png](https://images.zenhubusercontent.com/63d2ba5f1ae88085c27b0f0f/58ad49a1-1666-4e9b-9b2c-b0ea6620b9db)

**Comment by hfinney** [comment]
@jmiecz  @VitaliKrasnik let's go to 2 columns on smaller screens. I think retaining the readability of the word is top priority

**Comment by VitaliKrasnik** [comment]
@jmiecz  @hfinney Increased padding for smaller devices.
