### ISSUE TITLE
Android > Settings Screen

### ISSUE THREAD

**Issue by corblng** [LibertyDSNP/dsnp-wallet-kotlin#58]
**Narrative:** 
As a user, I would like to have a settings screen, so that I can easily manage and customize app settings at a global level.

**Overview:** 
This story is to create a "Settings" screen that will be the home for global app settings. 

**Figma Link**
https://www.figma.com/file/PDzDCWcPnZ8EFmwf5FkkBn/Amplica-Pro---MVP?type=design&node-id=1%3A1804&t=cMVKrSCRSubauYDz-1

**Requirements**
* Screen design and layout should match what is displayed in figma doc. Link above. 
* In order to access the Settings screen, a "Settings" button should be displayed in the bottom tab bar. Label "Settings" 
* Screen heading label "Settings" 
* Copy should match what is in the figma doc. Link above
* Button "Reveal Recovery Phrase" should be displayed. Tapping on button should direct user to the "There will be a test" flow. 
* FaceID, TouchID section should be displayed. Create a toggle that allows user to turn biometrics  ON/OFF  *Functionality for this will be part of another story. This is just showing the section / toggle in the Settings screen .

**Comment by VitaliKrasnik** [comment]
Verified
