### ISSUE TITLE
Android > Identity Screen

### ISSUE THREAD

**Issue by corblng** [LibertyDSNP/dsnp-wallet-kotlin#59]
**Narrative**:
As a user,  I would like to see a social identity screen in Amplica Access Pro, so that I can view and manage my social identity whenever I want. 

**Overview**: 
This story is to support building out an social identity screen. This screen will allow users to see their social identity (user handle) and over time evolve to include more metadata options that will serve as a "control center" for users to edit as they see fit. 

**Resource Link**: 
https://www.figma.com/file/PDzDCWcPnZ8EFmwf5FkkBn/Amplica-Pro---MVP?type=design&node-id=1%3A2031&t=BvxZCzC2Cr5rnHfT-1

**Requirements**: 
* Design screen to match what is displayed in figma comps
* Show static default profile pic as shown in figma *Note that avatar support will be a separate story. 
* Show user handle below default profile pic. Full handle should be displayed user handle+suffix 
* Show "Social Identity Complete" progress section. Include progress meter and step 1/x to complete. As user completes  profile setup steps, the progress meter should update. 
* Show "See All" button text link that directs user to Social Identity Progress screen.

**Comment by VitaliKrasnik** [comment]
Functional issue: 

The identity screen should show the new user handle (created handle) but now it uses a static from the design document. 

Steps: 
Do a fresh start for the app 
1. Create an identity starting from a landing page using a custom handle like : 'Test123'
2. On the congratulations screen click on the 'Skip for now' button

Expected result: The user handle below the default profile pic is 'Test123'
Actual result: The user handle below the default profile pic is 'neverendingwinter.23'

![image.png](https://images.zenhubusercontent.com/63d2ba5f1ae88085c27b0f0f/1d3ce9d9-dd9a-400c-89bb-3c9db69f91d0)

**Comment by VitaliKrasnik** [comment]
Tested Appcenter build : 84
