### ISSUE TITLE
Android > Existing DSNP ID Flow > Lookup By Email

### ISSUE THREAD

**Issue by crbnlng** [LibertyDSNP/dsnp-wallet-kotlin#6]
**Narrative** 
As a user, I would like to be able to lookup by DSNP ID (with my MeWe email address), so that I can easily migrate my account to the standalone wallet. 

 **Overview** 
This story is to build out the DSNP lookup by email flow. 

**Figma Link:** 
https://www.figma.com/file/JacuBzETlFr0VNjBQKKRgi/Wallet-Concepts?node-id=1161%3A3038&t=GxoyoBgW8ek8Y4Rw-1

 **Requirements**
- Screen designs should appear as they do in Figma *link below 
- On entry to DSNP ID lookup screen, the text field should be auto selected and keyboard should be visible. Alphabetical keyboard should be used
- Valid email address should be required for Send Auth Code button to highlight 
- Tapping on Restore DSNP Wallet should direct user to "Enter Seedphrase" screen 
- Use same placeholder Terms and Privacy Policy links that were used in the Welcome page. 
- Once valid email has been submitted the "Enter Code" screen should be displayed. 
- If  auth code entered is valid, proceed to seedphrase creation flow. 
- If auth code entered is not valid, show error state

**Comment by VitaliKrasnik** [comment]
Issues 
1. name@email.com should be used as a placeholder instead of name@gmail.com 
2. The Send Auth Code button should be disabled until a valid structured email address is entered 
![image.png](https://images.zenhubusercontent.com/63c04b69711e4943c2b9a622/2f6c262a-370e-4a07-88c4-22370b6c9eb9)

**Comment by VitaliKrasnik** [comment]
Can't validate an error message for an invalid One Time Code.

**Comment by VitaliKrasnik** [comment]
The design for an invalid email address is missing.

**Comment by VitaliKrasnik** [comment]
Not executed Tests: 
Verify that there is no error message shown when the email is valid but the user does not exist in the system 
Verify that a user gets an Error message If auth code entered is not valid, show the error state
