### ISSUE TITLE
Android: Social Identity: Progress Screen

### ISSUE THREAD

**Issue by corblng** [LibertyDSNP/dsnp-wallet-kotlin#60]
**Narrative**:
As a user, I would like to see suggested steps for updating my social identity, so that I can get the most out of my social web experience. 

**Overview** 
This story is to create the Social Identity: Progress Screen. This screen is designed to highlight key features that are important so users get the most out of their experience on the social web. The screen will contain a list of tasks for users to complete. After completing the task, a check will be displayed next to it to indicate completion. 

Resource Link: 
https://www.figma.com/file/PDzDCWcPnZ8EFmwf5FkkBn/Amplica-Pro---MVP?type=design&node-id=1%3A2133&t=BvxZCzC2Cr5rnHfT-1

**Requirements**: 
* Design of screen should match Figma comp
* Show header "Social Identity" 
* Show "Back" button. Tapping button should direct the user back to the social identity screen. 
* Show "Social Identity Progress" indicator with steps needed to complete i.e. 1/x. Completing a step should update the progress meter and step count. 
* Show copy that is displayed in figma *Note: this is not final and will be updated later under another story. 
* Show Step buttons. If step has been completed; show as visually indicated in figma with green check mark. 
* If task is NOT complete, show as visually indicated in Figma comp. 
* Show tasks: Backup Recovery Phrase, Choose Handle *Note that for MVP, almost all users will have a user handle and since we are only focused on migration of existing users (custodial to non-custodial) this will be more than likely be checked for these users.

**Comment by VitaliKrasnik** [comment]
The Implementation meets all acceptance criteria. 
App Center Build: 77
