### ISSUE TITLE
Android > Restore Wallet Flow

### ISSUE THREAD

**Issue by corblng** [LibertyDSNP/dsnp-wallet-kotlin#62]
**Narrative:** 
As a user, I would like to be able to restore my wallet using my secret recovery phrase, so that I can easily recover my data 

**Overview:** 
This story is to implement the Restore Wallet flow. Upon successfully entering their 12 word recovery phrase, the user should be able to recover their MSA, user handle and associated keys. 

**Figma Link**
https://www.figma.com/file/PDzDCWcPnZ8EFmwf5FkkBn/Amplica-Pro---MVP?type=design&node-id=1%3A10667&t=TWTsARJcVqiqZ2Az-1

**Requirements**
* User should see text button link on the landing screen labeled "Restore Account" 
* Tapping on the "Restore Acount" text button link should direct the user to the "Import Account" screen. 
* Screen and copy should appear as it does in figma link. 
* Upon page entry, description text as shown in figma should be displayed. Tapping into the text box should clear text and show cursor and auto launch keyboard. 
* User should be able type in their recovery phrase 
* User should be able to paste in their recovery phrase 
* Note: For initial launch we will do limited error handling. We will not try to correct or provide specific error messages based on what user entered in the text field. 
* Connect button should not be selectable until 12 words have been entered into text box. 
* Each word should be separated by a space. 
* If user enters the incorrect recovery phrase, show error messaging as shown in figma
* Tapping "Try Again" should clear word list and allow user to begin from the start. 
* Upon successful entry of recovery phrase, user should be directed to the Identity screen

**Comment by VitaliKrasnik** [comment]
The footer is located under the input field when the keyboard is shown on Samsung device S20  

![image.png](https://images.zenhubusercontent.com/63d2ba5f1ae88085c27b0f0f/e875e5a8-1cfe-41f6-ae3c-ce4afda8163d)

That's how it looks on emulator Pixel 6

https://images.zenhubusercontent.com/63d2ba5f1ae88085c27b0f0f/3694e2de-0b45-45c0-bccf-5345eef369d7

**Comment by VitaliKrasnik** [comment]
The button is enabled when one word is entered

![image.png](https://images.zenhubusercontent.com/63d2ba5f1ae88085c27b0f0f/7a1a523a-36ed-4bb8-acf4-b25718944803)

**Comment by VitaliKrasnik** [comment]
A previous error message is preserved after a user taps on the 'cancel' link and returns back to the restore screen again. 

Steps: 
1. Enter an invalid seed phrase and tap the 'connect' button -> The error message is shown
2. Tap on the cancel button -> the Landing page is opened 
3. Tap on the 'Restore' link 

Expected result: Previous error message was removed and the user can start entering the seed phrase from the beginning  
Actual result: The previous error message is preserved

**Comment by VitaliKrasnik** [comment]
This requirement was updated recently but also needs to be implemented as part of the fixes

* Tapping "Try Again" should clear word list and allow user to begin from the start.

**Comment by VitaliKrasnik** [comment]
@jmiecz please also fix this issue as well 
![image.png](https://images.zenhubusercontent.com/63d2ba5f1ae88085c27b0f0f/43c77f70-0fb2-4d8f-92e0-00ee54a36d01)

**Comment by VitaliKrasnik** [comment]
Tested Build: 87
