### ISSUE TITLE
Android > Create and Confirm Seed Phrase Flow

### ISSUE THREAD

**Issue by crbnlng** [LibertyDSNP/dsnp-wallet-kotlin#8]
**Narrative** 
As a user, I would like to understand the importance of backing up my seed phrase, so that I am in control of my data and can restore my wallet at a later time. 

 **Overview** 
Users will need to generate and confirm a seed phrase in order to take control of their DSNP ID profile. This story is to create the generation and confirm flow. 

Figma Link: 
https://www.figma.com/file/JacuBzETlFr0VNjBQKKRgi/Wallet-Concepts?node-id=1161%3A3038&t=GxoyoBgW8ek8Y4Rw-1

 **Requirements**
- Seed Phrase screens should match Figma designs 
- Standalone wallet app should be able to generate a 12 word seed phrase. 
- After seed phrase is generated and user taps "I've written it down" button, an alert should be displayed informing user that they will not be able to access the seed phrase once they continue. 
- Tapping "Check again" should return user to the seed phrase screen. Seed phrase should be the same and should not change if a user selects "Check again" 
- If user selects YES, then display "This is a Test" screen where they can confirm the seed phrase. 
- Tapping on word should input the word into the numbered boxes in ascending order. If user makes a mistake, they can tap on the word in the numbered box and it will return to the bottom selection list. 
- If seed phrase is entered incorrectly, error messaging should be displayed *see Figma
- If seed phrase is entered correctly then proceed to create device pin code flow

**Comment by DannyAhmedApex** [comment]
On smaller screen the cell is not adjusting correctly

**Comment by DannyAhmedApex** [comment]
Write a Static Seed Phrase is showing for the user, later on, will create a seed phrase programmatically

**Comment by VitaliKrasnik** [comment]
Issues 
1. 'In order' phrase should be Bold in the Sentence 'You will confirm them in order on the next screen.'
<img width="100" alt="image" src="https://user-images.githubusercontent.com/21163633/213883366-fbf6882e-d715-45b1-bc2a-c84f0c173f8a.png">
2. Suggestion to make the font bigger for the text on the Seed phrase page. 
3. According to the design a selected word should be removed from a cell at the bottom 
<img width="100" alt="image" src="https://user-images.githubusercontent.com/21163633/213883583-b0ba9925-cb90-43a0-b561-2e4b45ce45ef.png">
<img width="100" alt="image" src="https://user-images.githubusercontent.com/21163633/213883621-a47cda61-d947-499c-aa09-b5cfbcaad911.png">
4. The continue button should be enabled after all words are selected 
<img width="100" alt="image" src="https://user-images.githubusercontent.com/21163633/213883715-82803180-9d49-4b41-a8b1-bfb6dbd70b9b.png">
5. The Order in the grid should be different 

<img width="100" alt="image" src="https://user-images.githubusercontent.com/21163633/213884008-05554f85-3af1-4486-a0cd-004d0e453dfc.png">

<img width="100" alt="image" src="https://user-images.githubusercontent.com/21163633/213883985-48e5daf4-85ee-4c60-baa8-8a8d17ae567e.png">

**Comment by DannyAhmedApex** [comment]
Below points are fixed

- 'In order' phrase should be Bold in the Sentence 'You will confirm them in order on the next screen.'
- Suggestion to make the font bigger for the text on the Seed phrase page. 
- According to the design a selected word should be removed from a cell at the bottom
- The continue button should be enabled after all words are selected
- The Order in the grid should be different
