### ISSUE TITLE
Adding test tags for Android

### ISSUE THREAD

**Issue by jmiecz** [LibertyDSNP/dsnp-wallet-kotlin#83]
Adding the test tests to all components on Android

`Tag.kt`
```
sealed class Tag {
    object LandingScreen: Tag() {
        val testField = "test"
    }
}

fun Sample() {
    Tag.LandingScreen.testField
}
```

**Comment by VitaliKrasnik** [comment]
Hi @jmiecz  But I can't see the 'test' tag on the landing screen, what element is it attached to?

**Comment by jmiecz** [comment]
https://github.com/LibertyDSNP/dsnp-wallet-kotlin/blob/dev/app/src/main/java/com/unfinished/dsnp_wallet_kotlin/util/Tag.kt#L60
@VitaliKrasnik I've made every tag match their screen name 1:1 :)
